hardware:
  arduino:
    baudrate: 115200
    port: COM7
  motor:
    baudrate: 57600
    device: COM11
    ids:
    - 1
    - 2
normalization:
  max_handle_force: 20.0
  max_joint_angle: 0.5
  max_joint_velocity: 6.0
  max_wheel_force: 50.0
observation:
  history_length: 4
policy:
  control_frequency: 50.0
  device: cpu
  model_path: /path/to/your/rsl_rl_checkpoint.pt
safety:
  emergency_angle_limit: 0.4
  max_episode_steps: 400
